### ISSUE TITLE
"Create a real-time inferencing service" entry script doesn't recognise azureml.api

### ISSUE THREAD

**Issue by andrewblance** [MicrosoftLearning/mslearn-dp100#38] opened 2021-08-13 10:26 UTC
Hello! I am working my way through this azureML course - these notebooks are very helpful, thank you!

In 09-Create a real-time inferencing service I am finding an error though I cannot find a solution to. The model cannot seem to deploy. I have deleted it and tried again, tried changing python versions, and adding more imports to the entry script.

To be precise, when I run the cell that contains:

```
Error in entry script, ModuleNotFoundError: No module named 'azureml.api', please run print(service.get_logs()) to get details.
```

the model fails to deploy, giving me the error:

```
Error:
{
  "code": "AciDeploymentFailed",
  "statusCode": 400,
  "message": "Aci Deployment failed with exception: Error in entry script, ModuleNotFoundError: No module named 'azureml.api', please run print(service.get_logs()) to get details.",
  "details": [
    {
      "code": "CrashLoopBackOff",
      "message": "Error in entry script, ModuleNotFoundError: No module named 'azureml.api', please run print(service.get_logs()) to get details."
    }
  ]
}

---------------------------------------------------------------------------
WebserviceException                       Traceback (most recent call last)
<ipython-input-9-ca23bdb13d88> in <module>
     13 service = Model.deploy(ws, service_name, [model], inference_config, deployment_config)
     14 
---> 15 service.wait_for_deployment(True)
     16 print(service.state)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/core/webservice/webservice.py in wait_for_deployment(self, show_output, timeout_sec)
    923                                           'Error:\n'
    924                                           '{}'.format(self.state, self._operation_endpoint.split('/')[-1],
--> 925                                                       logs_response, format_error_response), logger=module_logger)
    926             print('{} service creation operation finished, operation "{}"'.format(self._webservice_type,
    927                                                                                   operation_state))

WebserviceException: WebserviceException:
	Message: Service deployment polling reached non-successful terminal state, current service state: Failed
Operation ID: 8243c85c-0232-4b65-8c23-710ae73d1a63
More information can be found using '.get_logs()'
Error:
{
  "code": "AciDeploymentFailed",
  "statusCode": 400,
  "message": "Aci Deployment failed with exception: Error in entry script, ModuleNotFoundError: No module named 'azureml.api', please run print(service.get_logs()) to get details.",
  "details": [
    {
      "code": "CrashLoopBackOff",
      "message": "Error in entry script, ModuleNotFoundError: No module named 'azureml.api', please run print(service.get_logs()) to get details."
    }
  ]
}
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Service deployment polling reached non-successful terminal state, current service state: Failed\nOperation ID: 8243c85c-0232-4b65-8c23-710ae73d1a63\nMore information can be found using '.get_logs()'\nError:\n{\n  \"code\": \"AciDeploymentFailed\",\n  \"statusCode\": 400,\n  \"message\": \"Aci Deployment failed with exception: Error in entry script, ModuleNotFoundError: No module named 'azureml.api', please run print(service.get_logs()) to get details.\",\n  \"details\": [\n    {\n      \"code\": \"CrashLoopBackOff\",\n      \"message\": \"Error in entry script, ModuleNotFoundError: No module named 'azureml.api', please run print(service.get_logs()) to get details.\"\n    }\n  ]\n}"
    }
}
```

I have tried this in the browser instance of jupyter notebooks provided in AzureML, and also on my local version of Visual Studio Code using the AzureML plugin. 

Can I please get some advice on how to proceed?

Thanks

**Comment by GraemeMalcolm** [comment] 2021-08-13 15:58
Hi @andrewblance ,
This is a duplicate of issue [37](https://github.com/MicrosoftLearning/mslearn-dp100/issues/37) and has been resolved. Please re-pull the latest notebooks from the repo

**Closed by GraemeMalcolm** 2021-08-13 15:58 UTC
