### ISSUE TITLE
Creating conda environment failed with exit code: -15

### ISSUE THREAD

**Issue by mkrasmus** [MicrosoftLearning/mslearn-dp100#34] opened 2021-06-19 12:26 UTC
05 - Train Models.ipynb produces an error @ the chunk following **Run the training script as an experiment**.

Kernal: **Python 3.6 - AzureML**
Compute instance: **STANDARD_DS1_V2**

When I run:

```
from azureml.core import Experiment, ScriptRunConfig, Environment
from azureml.core.conda_dependencies import CondaDependencies
from azureml.widgets import RunDetails

# Create a Python environment for the experiment
sklearn_env = Environment("sklearn-env")

# Ensure the required packages are installed (we need pip, scikit-learn and Azure ML defaults)
packages = CondaDependencies.create(conda_packages=['pip', 'scikit-learn'],
                                    pip_packages=['azureml-defaults'])
sklearn_env.python.conda_dependencies = packages

# Create a script config
script_config = ScriptRunConfig(source_directory=training_folder,
                                script='diabetes_training.py',
                                environment=sklearn_env) 

# submit the experiment run
experiment_name = 'mslearn-train-diabetes'
experiment = Experiment(workspace=ws, name=experiment_name)
run = experiment.submit(config=script_config)

# Show the running experiment run in the notebook widget
RunDetails(run).show()

# Block until the experiment run has completed
run.wait_for_completion()
```

I get:

```
---------------------------------------------------------------------------
ActivityFailedException                   Traceback (most recent call last)
<ipython-input-6-080c54dc6996> in <module>
     25 
     26 # Block until the experiment run has completed
---> 27 run.wait_for_completion()

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/core/run.py in wait_for_completion(self, show_output, wait_post_processing, raise_on_error)
    822 
    823                 if raise_on_error:
--> 824                     raise ActivityFailedException(error_details=json.dumps(error, indent=4))
    825 
    826             return final_details

ActivityFailedException: ActivityFailedException:
	Message: Activity Failed:
{
    "error": {
        "code": "UserError",
        "message": "Creating conda environment failed with exit code: -15",
        "messageParameters": {},
        "details": []
    },
    "time": "2021-06-19T12:21:20.816582Z"
}
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Activity Failed:\n{\n    \"error\": {\n        \"code\": \"UserError\",\n        \"message\": \"Creating conda environment failed with exit code: -15\",\n        \"messageParameters\": {},\n        \"details\": []\n    },\n    \"time\": \"2021-06-19T12:21:20.816582Z\"\n}"
    }
}
```

**Comment by GraemeMalcolm** [comment] 2021-06-19 15:03
Confirmed - I can repro this.
I'm investigating...

**Comment by GraemeMalcolm** [comment] 2021-06-19 15:59
I've reached out to the Azure ML product team for help. I'll post here as soon as I have any information.

**Comment by mkrasmus** [comment] 2021-06-19 22:40
Thank you, my workaround provided by a [stackoverflow](https://stackoverflow.com/questions/67639665/azure-ml-not-able-to-create-conda-environment-exit-code-15) solution. Created an environment with the same specs.

**Comment by GraemeMalcolm** [comment] 2021-06-20 00:24
Yup - it looks like the Conda spec created by the CondaDependencies object is not quite right. Using my own .yml file resolves it.
I'll update the labs to use this approach - not sure why this has suddenly stopped working though!

**Comment by GraemeMalcolm** [comment] 2021-06-20 02:20
OK, so I've pushed updates to all of the notebooks so we use a .yml file to create the environment rather than CondaDependencies.
If you've already cloned the repo, you'll need to pull it to get the updated notebooks (and the environment.yml file in the root used in the first couple of notebooks)
I'll do another end-to-end test tomorrow, and close this issue when the fix is verified.

**Comment by GraemeMalcolm** [comment] 2021-06-20 23:18
End-to-end test completed successfully. Closing this issue now.

**Closed by GraemeMalcolm** 2021-06-20 23:18 UTC
