### ISSUE TITLE
Create a batch inferencing module error due to undersized compute configuration

### ISSUE THREAD

**Issue by mkrasmus** [MicrosoftLearning/mslearn-dp100#35] opened 2021-06-21 13:18 UTC
I am getting the following error when stepping through the scripts for the batch inferencing module:
```
"Job submission to AzureML Compute encountered an Exception with status code JobNodeCountExceedsCoreQuota, The specified subscription has a Standard DSv2 family vCPU quota of 2 and is less than the requested job node count of 2 which maps to 4 vCPUs. Talk to your Subscription Admin or refer to https://docs.microsoft.com/azure/machine-learning/how-to-manage-quotas#request-quota-increases to increase the Standard DSv2 family vCPU quota\"
```
Not however that the script provided includes the following:
```
try:
    # Check for existing compute target
    inference_cluster = ComputeTarget(workspace=ws, name=cluster_name)
    print('Found existing cluster, use it.')
except ComputeTargetException:
    # If it doesn't already exist, create it
    try:
        compute_config = AmlCompute.provisioning_configuration(vm_size='STANDARD_DS11_V2', max_nodes=2)
        inference_cluster = ComputeTarget.create(ws, cluster_name, compute_config)
        inference_cluster.wait_for_completion(show_output=True)
    except Exception as ex:
        print(ex)
```
Suggesting that the above compute configuration is not enough.

**Comment by GraemeMalcolm** [comment] 2021-06-21 15:43
It looks like (a.) You already have a compute cluster with the name you specified that's using the Standard_DS2_V2 size (otherwise the code would have created a Standard_DS11_V2 cluster), and (b.) Your subscription has a quota limit of 2 cores for a Standard_DS2_V2 VM. The problem is that the batch job uses 2 nodes in parallel, but there are 2 cores per node - which is more than your quota allows.

What kind of subscription are you using?

**Comment by GraemeMalcolm** [comment] 2021-06-22 15:23
Closing this as the issue appears to be specific to the subscription being used, not the lab content.

**Closed by GraemeMalcolm** 2021-06-22 15:23 UTC
