### ISSUE TITLE
Detect Unfairness lab error

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/mslearn-dp100#106] opened 2023-01-25 20:31 UTC
Lab: Detect Unfairness
Cell: 8

Updating to Flask 2.0.1 + resolves the issue. Reported in StackOverflow: https://stackoverflow.com/questions/71189819/importerror-cannot-import-name-json-from-itsdangerous

from raiwidgets import FairnessDashboard import method generates error: 

ImportError                               Traceback (most recent call last)
Cell In [8], line 1
----> 1 from raiwidgets import FairnessDashboard

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/raiwidgets/__init__.py:6
      1 # Copyright (c) Microsoft Corporation
      2 # Licensed under the MIT License.
      4 """Package for the fairness, explanation, and error analysis widgets."""
----> 6 from .fairness_dashboard import FairnessDashboard
      7 from .explanation_dashboard import ExplanationDashboard
      8 from .error_analysis_dashboard import ErrorAnalysisDashboard

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/raiwidgets/fairness_dashboard.py:6
      1 # Copyright (c) Microsoft Corporation
      2 # Licensed under the MIT License.
      4 """Defines the fairness dashboard class."""
----> 6 from .dashboard import Dashboard
      7 from .fairness_metric_calculation import FairnessMetricModule
      8 from responsibleai._input_processing import _convert_to_string_list_dict,\
      9     _convert_to_list

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/raiwidgets/dashboard.py:11
      8 import uuid
     10 from html.parser import HTMLParser
---> 11 from rai_core_flask import FlaskHelper  # , environment_detector
     13 from responsibleai.serialization_utilities import serialize_json_safe
     16 class InLineScript(HTMLParser):

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/rai_core_flask/__init__.py:6
      1 # Copyright (c) Microsoft Corporation
      2 # Licensed under the MIT License.
      4 """Module for wrapped-flask service."""
----> 6 from .flask_helper import FlaskHelper
      8 __all__ = ['FlaskHelper']

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/rai_core_flask/flask_helper.py:4
      1 # Copyright (c) Microsoft Corporation
      2 # Licensed under the MIT License.
----> 4 from flask import Flask
      5 from .environment_detector import build_environment
      6 from .environments.credentialed_vm_environment import CREDENTIALED_VM

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/flask/__init__.py:21
     18 from werkzeug.utils import redirect
     19 from jinja2 import Markup, escape
---> 21 from .app import Flask, Request, Response
     22 from .config import Config
     23 from .helpers import url_for, flash, send_file, send_from_directory, \
     24      get_flashed_messages, get_template_attribute, make_response, safe_join, \
     25      stream_with_context

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/flask/app.py:26
     21 from werkzeug.exceptions import BadRequest, BadRequestKeyError, HTTPException, \
     22     InternalServerError, MethodNotAllowed, default_exceptions
     23 from werkzeug.routing import BuildError, Map, RequestRedirect, \
     24     RoutingException, Rule
---> 26 from . import cli, json
     27 from ._compat import integer_types, reraise, string_types, text_type
     28 from .config import Config, ConfigAttribute

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/flask/json/__init__.py:21
     17 from jinja2 import Markup
     19 # Use the same json implementation as itsdangerous on which we
     20 # depend anyways.
---> 21 from itsdangerous import json as _json
     24 # Figure out if simplejson escapes slashes.  This behavior was changed
     25 # from one version to another without reason.
     26 _slash_escape = '\\/' not in _json.dumps('/')

ImportError: cannot import name 'json' from 'itsdangerous' (/anaconda/envs/azureml_py38/lib/python3.8/site-packages/itsdangerous/__init__.py)

**Comment by madiepev** [comment] 2023-02-02 14:32
Thanks for reporting this. We couldn't reproduce the error. Try restarting the kernel after the pip install. Additionally, you can also try to install the package without the specific version.

**Comment by madiepev** [comment] 2023-02-09 10:48
I've made some tweaks to the lab that may prevent this issue and added a note to restart the kernel if the dashboard doesn't show. Will close the issue for now.

**Closed by madiepev** 2023-02-09 10:48 UTC
