### ISSUE TITLE
14 - Interpret Models

### ISSUE THREAD

**Issue by AdolfoG22** [MicrosoftLearning/mslearn-dp100#75] opened 2022-04-08 14:19 UTC
I just tested this notebook with the Runtime: Python 3.8 - Azure ML
Cell No. 10

**Error occurred:** Unable to run conda package manager. AzureML uses conda to provision python environments from a dependency specification. 

[2022-04-08T14:13:20.646586] Using urllib.request Python 2
Streaming log file azureml-logs/60_control_log.txt
Starting the daemon thread to refresh tokens in background for process with pid = 4641
Running: ['/bin/bash', '/tmp/azureml_runs/mslearn-diabetes-explain_1649427199_4886c13b/azureml-environment-setup/conda_env_checker.sh']
Materialized conda environment not found on target: /home/azureuser/.azureml/envs/azureml_4612c5564caffc186e5bd2016e43147c
[2022-04-08T14:13:20.755812] Logging experiment preparation status in history service.
Running: ['/bin/bash', '/tmp/azureml_runs/mslearn-diabetes-explain_1649427199_4886c13b/azureml-environment-setup/conda_env_builder.sh']
Running: [u'conda', '--version']
[Errno 2] No such file or directory
()
Unable to run conda package manager. AzureML uses conda to provision python
environments from a dependency specification. To manage the python environment
manually instead, set userManagedDependencies to True in the python environment
configuration. To use system managed python environments, install conda from:
https://conda.io/miniconda.html
()
[2022-04-08T14:13:22.165785] Logging error in history service: Failed to run ['/bin/bash', '/tmp/azureml_runs/mslearn-diabetes-explain_1649427199_4886c13b/azureml-environment-setup/conda_env_builder.sh'] 
 Exit code 1 
Details can be found in azureml-logs/60_control_log.txt log file.

Uploading control log...

Error occurred: Unable to run conda package manager. AzureML uses conda to provision python
environments from a dependency specification. To manage the python environment
manually instead, set userManagedDependencies to True in the python environment
configuration. To use system managed python environments, install conda from:
https://conda.io/miniconda.html

Thank you

**Comment by GraemeMalcolm** [comment] 2022-04-08 15:02
When did you pull the notebooks? (they were all updated yesterday to address the Python version issues)

**Comment by AdolfoG22** [comment] 2022-04-08 15:08
I did the exercise with the new notebooks today, a few minutes ago

**Comment by GraemeMalcolm** [comment] 2022-04-08 15:10
And you provisioned a new workspace? (just trying to eliminate the most obvious causes)

**Comment by AdolfoG22** [comment] 2022-04-08 15:11
Yes, I deleted all resources in Azure and re-provisioned a new WorkSpace today.

**Comment by GraemeMalcolm** [comment] 2022-04-08 15:21
Yup - confirmed. I get the same error. @madiepev , can you take a look? Seems to be an issue with the experiment environment.

**Comment by AdolfoG22** [comment] 2022-04-08 15:38
I think it may be some version of the CONDA libraries inside the new images that were published in Azure recently

**Comment by GraemeMalcolm** [comment] 2022-04-08 15:39
Fixed by adding code to assign a DockerConfiguration

**Closed by GraemeMalcolm** 2022-04-08 15:39 UTC

**Comment by AdolfoG22** [comment] 2022-04-08 15:41
Thank you
