### ISSUE TITLE
Lab 3A: Widget is not loaded

### ISSUE THREAD

**Issue by instrovatesimran1** [MicrosoftLearning/mslearn-dp100#78] opened 2022-05-26 15:52 UTC
when using the code:
from azureml.widgets import RunDetails
   RunDetails(run).show()

The widgets are not getting loaded.

**Comment by madiepev** [comment] 2022-05-27 09:54
@instrovatesimran1 where are you running the notebook? Is it in the Azure Machine Learning Studio?

**Comment by instrovatesimran1** [comment] 2022-05-27 12:30
Yes

**Comment by madiepev** [comment] 2022-05-31 17:51
@instrovatesimran1 I'm not able to reproduce your error. It may be a bug in the Studio. Please use the feedback/support option in the Studio to report the bug. I'll close the issue for now.

**Closed by madiepev** 2022-05-31 17:51 UTC
