### ISSUE TITLE
Designer deployment failure?

### ISSUE THREAD

**Issue by GraemeMalcolm** [MicrosoftLearning/mslearn-dp100#48] opened 2021-09-28 15:46 UTC
Report that https://microsoftlearning.github.io/mslearn-dp100/instructions/03-azureml-designer.html fails at the deployment step.
@madiepev , can you take a look? (may also affect Designer modules on Learn)

**Comment by madiepev** [comment] 2021-09-30 10:54
It's an known issue caused by unexpected module version upgrade. It's been resolved by applying hotfix to all regions. For users, please rerun training pipeline by check on "Regenerate Output", and run corresponding inference pipeline and try deployment again.

**Closed** 2021-09-30 22:27 UTC
